#
# Builder
#

FROM alpine AS builder

ARG plugins="http.cache,http.filter,http.webdav,tls.dns.cloudflare"

RUN apk update \
    && apk add --no-cache bash ca-certificates gzip curl \
    && curl https://getcaddy.com | bash -s personal ${plugins}

#
# Final stage
#

FROM scratch
LABEL maintainer "Abiola Ibrahim <abiola89@gmail.com>"

# Let's Encrypt Agreement
ENV ACME_AGREE="false"

# install caddy
COPY --from=builder /usr/local/bin/caddy /usr/bin/caddy

# validate install
#RUN /usr/bin/caddy -version
#RUN /usr/bin/caddy -plugins

EXPOSE 80 443 2015

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY Caddyfile /etc/Caddyfile

ENTRYPOINT ["caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=true", "-quic"]
